output_dir: test/sft
# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B
tokenizer_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: "flash_attention_2"
max_seq_length: 2048

# Dataset 
dataset_id_or_path: "HuggingFaceH4/no_robots"
dataset_splits: "train"
packing: true

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: "all-linear"
merge_adapters: true

# SFT trainer config
bf16: true
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
num_train_epochs: 3
learning_rate: 5.0e-05
lr_scheduler_type: cosine
warmup_ratio: 0.1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_steps: 10  
save_steps: 100
save_total_limit: 1
logging_strategy: steps
save_strategy: steps
eval_strategy: "no"
report_to:
- tensorboard
seed: 42
# hub strategy
# push_to_hub: true
# hub_strategy: every_save