num_iterations: 3
output_dir: test/iterative_dpo
# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
torch_dtype: bfloat16
attn_implementation: "flash_attention_2"

# Dataset 
dataset_id_or_path:  "HuggingFaceH4/ultrafeedback_binarized"
train_split: "train_prefs"

# Candiate Generation arguments
num_samples: 5
batch_size: 128 # 8x H100 80GB

# Ranking arguments
rank_model_name_or_path: RLHFlow/ArmoRM-Llama3-8B-v0.1
rank_trust_remote_code: true

# LoRA arguments
use_peft: false

# DPOTrainer arguments
bf16: true
beta: 0.01
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03 
log_level: info
logging_steps: 10
max_length: 1536
max_prompt_length: 768
optim: adamw_torch
per_device_train_batch_size: 4
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
