output_dir: test/offline_dpo-2
# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
torch_dtype: bfloat16
attn_implementation: "flash_attention_2"
# Dataset 
dataset_id_or_path:  "HuggingFaceH4/ultrafeedback_binarized"
dataset_splits: "train_prefs"
# LoRA arguments
use_peft: false

# DPOTrainer arguments
num_train_epochs: 1
bf16: true
beta: 0.01
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03 
log_level: info
logging_steps: 10
max_length: 1536
max_prompt_length: 768
optim: adamw_torch
per_device_train_batch_size: 4
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
